rentzsch/mogenerator

- templates/machine.h.motemplate
The keys "documentation" and "discussion" are used to get the information about the property.
Merging this will close issue #192.
> Add documentation generation using the User Info keys

- templates/machine.swift.motemplate
Swift classes in frameworks/dynamic libraries are inaccessible to clients unless they and their public API are declared `public`. A class may not be made public unless its superclass is also public.
So: If you want to expose `MyMogeneratedClass` in a dynamic library, you must also declare `_MyMogeneratedClass` `public`. This requires hand-editing `_MyMogeneratedClass.swift`, which defeats the purpose of machine-generated classes.
This revision adds the `public` qualifier to the class and `@NSManaged` properties in `machine.swift.motemplate`.
A subtler implementation might add a command-line argument to suppress or otherwise refine the use of `public`. However:
1. Nobody needs more command-line arguments. Ever.
2. Risk of accidental collisions between framework and client code is small …
> Swift: Make generated machine classes and their attributes public.

- test/Rakefile
Add quotes around calls to `Dir.pwd` so that tests run if the path contains spaces.
> Quote paths in test/Rakefile

- templates/machine.swift.motemplate
Fixes generated calls to unionOrderedSet and minusOrderedSet, which should not have their arguments downcast to Set<NSObject>.
> Fix swift template for ordered relationships.

- templates/machine.m.motemplate
Updated the machine.m template to use @[] and @{} literal syntax for arrays and dictionaries. 
These changes are enabled by the existing __literals__ template-var.
This changes are relevant for code that is generated for __Fetch Requests__ that are defined in the `.xcdatamodel` file.
> Using modern Objective C syntax: literals for arrays and dictionaries

- build-mogenerator-Info-plist.sh
- mogenerator.xcodeproj/project.pbxproj
TMPDIR is not well-defined, but DERIVED_FILE_DIR is during an Xcode build. 
Also, make sure paths are quoted.
> Update build-mogenerator-Info.plist.sh to use DERIVED_FILE_DIR instead of TMPDIR

- mogenerator.h
- mogenerator.m
- templates/machine.h.motemplate
- templates/machine.m.motemplate
- test/Rakefile
As part of modernizing mogenerator for a 2.0 (or whatever we call it), I’ve removed the —v2 argument and now we generate Objective-C using ARC, Objective-C literals, and modules out of the box.
There’s still some stuff I don’t like about our Objective-C code I’d like to fix. Namely, the structs for attribute names need to be marked `__unsafe_unretained` because ARC doesn’t support objects in a struct. I wasn’t sure of a better way to handle that without adding a bunch of extra code. 
I’d also like to add nullability attributes to Objective-C where appropriate, but we can save that for another day (Patches Welcomed!)
This is obviously a breaking change, and I always opt to go fairly heavy handed on that in favor of moving the project forward. Feedback welcomed.
> Default to --v2 arguments.

- mogenerator.m
- templates/machine.swift.motemplate
In the CoreData Model editor, an entity can have a specified module from which to be loaded. However, when specifying the current module, the entity class name is prepended with a ".". This is an invalid class name and also not helpful file name for the resulting generated files. The fix here is to check for the . and remove it in the file name and class name template.
> Sanitize managedObjectClassName specifiying the current module

- templates/human.h.motemplate
- templates/machine.h.motemplate
- templates/machine.m.motemplate
I'm working on getting our ObjC templates updates. 
Here's what's new in this one:
1. I replaced the old `struct` objects we were using for relationship and attribute names with first class `NSObject` instances. This lets us not annoy the Apple gods by putting NS objects inside structs, which is a no-no in ARC land. (`__unsafe_unretained` is cheating)
2. Added nullability attributes where appropriate for attributes, relationships, and fetched properties. 
I still want to add lightweight generic support, but that is going to require some internal surgery I think.
> Nullability & New Attribute Objects for Objective-C Templates

- templates/machine.h.motemplate
One line change to offer appropriate nullability in machine consumption headers.
Partially addresses https://github.com/rentzsch/mogenerator/issues/336
Because NSEntityDescription#entityForName:inManagedObjectContext: is
nullable
> Make entityInManagedObjectContext: nullable

- templates/machine.m.motemplate
If a to-many relationship property is nullable, the current CoreDataGeneratedAccessors template generates multiple nullability build errors when using -Wnullable-to-nonnull-conversion. This change is a naive fix for those errors but may be appropriate unless more detailed consideration of nullable properties is warranted.
Partially addresses https://github.com/rentzsch/mogenerator/issues/336
If, during CoreDataGeneratedAccessors, a relationship property is null,
fall back to a newly instantiated NSOrderedSet.
> Allow for nullable collection properties

- index.html
Updates the link to Apple's "Core Data Programming Guide".
**Note** The original link pointed to the Mac documentation, but it looks like the iOS and Mac URLs now link to the same content.
None
Apple loves to move pages around...
> Updates "Core Data Programming Guide" Link

- templates/machine.h.motemplate
Modified the machine template header to consider nullability for the getter and setter of a primitive defined attribute type.
A defined attribute can be nullable, so the getter and setter of the primitive should consider nullable.
> Add nullability to the primitive value

- mogenerator.h
- mogenerator.m
- momcom/NSAttributeDescription+momcom.h
- momcom/NSAttributeDescription+momcom.m
- templates/machine.swift.motemplate
The `Uses Scalar Type` checkbox was not handled and therefore when using a swift template the generated output was wrong. Instead of using scalars it was always generated as `NSNumber`.
Now it mimics the behaviour of the Xcode generator.
Because the `usesScalarValueType` is not (yet) available on `NSAttributeDescription` I used a `userInfo` entry to pass the value around.
> Support for “Uses Scalar Type”.

- mogenerator.m
Expose an allAttributes and allRelationships accessors so that code can be generated to also reference descriptions excluded by noninheritedAttributes and noninheritedRelationships.
Addresses [EntityAttributes should also be present in ChildEntity-Attributes](https://github.com/rentzsch/mogenerator/issues/328)
> Expose allAttributes and allRelationships, related to #328

- .travis.yml
- mogenerator.m
- momcom/NSAttributeDescription+momcom.m
- test/Rakefile
This adds support for generating accessors for `NSURIAttributeType` and `NSUUIDAttributeType` attributes, which were introduced in iOS 11 and macOS 10.13.
With the introduction of this change, the mogenerator binary must be built using Xcode 9.
> Add support for URI and UUID attribute types

- templates/machine.swift.motemplate
Calling `NSManagedObject.fetchRequest()` is invalid:
> This method is only legal to call on **subclasses of `NSManagedObject`** that represent a single entity in the model.
https://developer.apple.com/documentation/coredata/nsmanagedobject/1640605-fetchrequest
The proper way is to call good old `NSFetchRequest(entityName: self.entityName())`, which gets bridged to the specialized `NSFetchRequest<…>`.
> Fixed invalid call of `NSManagedObject.fetchRequest()`

- templates/machine.h.motemplate
Add nullability annotations for generated primitive accessors of optional, to-one relationships.
https://github.com/rentzsch/mogenerator/issues/361
> Nullability annotations for generated primitive accessors

- mogenerator.h
- mogenerator.m
Expose information when custom type is set through userInfo. This allows you to write custom getter/setter for these attributes in Swift.
Please see [my blog post](http://aplus.rs/2017/custom-typed-coredata-attributes/) for deeper explanation.
None.
> Expose information when custom type is set through userInfo

- mogenerator.h
- mogenerator.m
- test/Rakefile
- test/test.xcdatamodel/contents
Hi @rentzsch 
Recently I have been looking into using the _Xcode_ CoreData generated NSManagedObject subclasses. The code base we are working on is kind of big and we have **plenty** of _Mogenerator_ generated classes. 
In order to slowly migrate to the Xcode generated classes we need a way to use both generators at the same time. 
Xcode already supports this by allowing to enable/disable code generation per entity. This pull request adds support for ignoring entities when generating with _Mogenerator_ (I looked a bit but couldn't find any other solution to ignore entities).
Tests passed with `MacOSX10.14.sdk` and I added another test for checking if the parameter works.
Thank you and I am looking forward to your feedback!
> Add parameter to ignore entities

- mogenerator.m
That the custom base class is not sanitised (leading '.' from default/implicit module creeps in)
The filename has the same symptom except '.' gets replaced with '_', but in the case of the useless leading prefix, it ends up being '__' for machine file.
> Address #387, "Current Product Module" issues with swift/Xcode-11.3

- mogenerator.xcodeproj/project.pbxproj
When looking at Homebrew packages that no longer build correctly ( https://github.com/Homebrew/homebrew-core/issues/65000 ) I decided to take a quick look at mogenerator although I didn't know anything about the package before.
The build failure at first seemed very odd.  The final link was failing with:
```
error: Build input file cannot be found: '[...]/objroot/mogenerator.build/Release/mogenerator.build/DerivedSources/mogenerator-Info.plist' [...]
```
At first I assumed that the `build-mogenerator-Info-plist.sh` script either did not run or failed to produce the expected file.  However, after adding some more debugging statements that does not seem to be the case.  The script definitely runs and you can see the output from PlistBuddy in the build output:
```
Unrecognized Type:
File …
```
> Try to fix Xcode 12 build (outputPaths from build-mogenerator-Info-plist.sh seems wrong)

- mogenerator.m
The previous implementation checked the validation predicate for a string containing literally ">= 0".  But if an attribute's minimum was, for example, 1 instead of 0, the test would fail because the string would be ">= 1".  But when a minimum is 1 we still want to use `unsigned`, but weren't getting `unsigned` because of this.
Updated the code to instead look for the string "SELF >=" and then inspect the number that comes after (if any). Then we can in fact correctly check that the minimus is >= 0, thus allowing `unsigned` to be used in those cases too.
> Improved isUnsigned to check attribute minimum more carefully

- mogenerator.m
- templates/machine.h.motemplate
- templates/machine.m.motemplate
No change in behaviour by default.
But now if the command line includes `--template-var include-ash-classes=false` then these classes will not be created.
If you don't use them, this reduces code size a bit (200 KB / 0.12 % in my case) and removes things from Xcode's autocomplete that are just clutter.
> issue #83: Added option to make Mike Ash-style classes optional
